sudo: required

services:
  - docker

env:
  global:
     - CLOUDSDK_CORE_DISABLE_PROMPTS: 1
     - GCLOUD_PROJECT: strapdata-gcp-partnership
     - GCLOUD_ZONE: europe-west1-b
     - GCLOUD_CLUSTER: elassandra-travis

cache:
  directories:
    - $HOME/google-cloud-sdk/

before_install:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud -v
  - echo "$GCLOUD_SECRET_KEY" | base64 -d > gcloud-secret.json
  - cat $GCLOUD_SECRET_KEY
  - gcloud auth activate-service-account --key-file gcloud-secret.json
  - cat gcloud-secret.json | docker login -u _json_key --password-stdin https://gcr.io
  - gcloud components install kubectl
  - gcloud components install beta
  - gcloud components update

install:
  - export GCLOUD_CLUSTER=${GCLOUD_CLUSTER}-$(head /dev/urandom | tr -dc 0-9 | head -c 4 ; echo '')
  - gcloud config set project $GCLOUD_PROJECT
  - gcloud config set compute/zone $GCLOUD_ZONE
  - PROJECT=$GCLOUD_PROJECT ZONE=$GCLOUD_ZONE CLUSTER=$GCLOUD_CLUSTER bash ./setup-k8s.sh
  - kubectl config get-contexts

script:
  - REPO_NAME=elassandra-staging make app/build
  - REPO_NAME=elassandra-staging make app/verify

after_success:
  - gcloud container clusters delete $GCLOUD_CLUSTER --region $GCLOUD_ZONE

after_failure:
  - gcloud container clusters delete $GCLOUD_CLUSTER --region $GCLOUD_ZONE

deploy:
  - provider: script
    skip_cleanup: true
    script: REPO_NAME=elassandra make app/build
    on:
      tags: true
